enable-module-update = true # set this to false if you do not want to receive updates for the module
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube-Morphe]
app-name = "YouTube"
version = "uptodown_latest"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "module"
patches-version = "dev"
arch = "arm64-v8a"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
excluded-patches = "'Alternative thumbnails' 'Ambient mode' 'Change form factor' 'Change start page' 'Copy video URL' 'Custom branding' 'Custom player overlay opacity' 'Disable DRC audio' 'Disable QUIC protocol' 'Disable rolling number animations' 'Disable video codecs' 'Enable debugging' 'Exit fullscreen mode' 'GmsCore support' 'Hide autoplay preview' 'Open videos fullscreen' 'Override YouTube Music actions' 'Seekbar' 'Shorts autoplay'"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=@android:color/system_neutral1_900 -OlightThemeBackgroundColor=@android:color/system_neutral1_100"

[Music-Morphe]
app-name = "Music"
version = "uptodown_latest"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
patches-version = "dev"
arch = "arm64-v8a"
build-mode = "module"
excluded-patches = "'Custom branding' 'Disable DRC audio' 'Disable QUIC protocol' 'Enable debugging' 'GmsCore support'"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=@android:color/system_neutral1_900"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"

[IconPackStudio]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/icon-pack-studio/"
